Multiple bug fixes in pymgkemonitoringsetup

diff --git a/bin/pymgkemonitoringsetup b/bin/pymgkemonitoringsetup
--- a/bin/pymgkemonitoringsetup
+++ b/bin/pymgkemonitoringsetup
@@ -8,6 +8,8 @@
 set -e
 
 ARGS=$@
+LIVE=0
+STAGING=0
 
 usage() {
     cat << EOF
@@ -17,8 +19,10 @@ Install helm, tiller, prometheus and grafana in the staging and live
 environments.
 
 OPTIONS:
-  --debug           Debug verbosity.
-  --help            This text.
+  --live        Setup for the live cluster
+  --staging     Setup for the staging cluster
+  --debug       Debug verbosity.
+  --help        This text.
 
 EOF
 }
@@ -27,16 +31,16 @@ parse_args() {
     while [ "$1" != "" ]; do
         case $1 in
             "--debug")         set -x; DEBUG='true';;
-            "--no-test")       export DO_TEST=;;
             "-h" | "--help")   usage; exit 0;;
-            "--live-ip")       get_ip 'live'; exit 0;;
-            "--staging-ip")    get_ip 'staging'; exit 0;;
+            "--live")          export LIVE=1;;
+            "--staging")       export STAGING=1;;
             *)                 VERSION=$1;;
         esac
         shift
     done
 }
 
+parse_args $ARGS
 
 ROOTDIR=$(git rev-parse --show-toplevel)
 if [ "$PWD" != "$ROOTDIR" ]; then
@@ -61,6 +65,12 @@ check_rc() {
     fi
 }
 
+do_setup_glcoud() {
+    echo "=> Configuring gcloud..."
+    gcloud config set project $GCP_PROJECT
+    gcloud config set compute/region $GCP_REGION
+}
+
 do_create_namespace() {
     NAMESPACE=$1
     CNT=$(kubectl get namespace | grep "$NAMESPACE " | wc -l)
@@ -72,8 +82,25 @@ do_create_namespace() {
     kubectl config set-context --current --namespace=$NAMESPACE
 }
 
+do_install_helm_app() {
+    HELM_APP=$1
+    CNT=$(kubectl get pods --namespace monitoring | grep $HELM_APP | wc -l)
+    if [ $CNT -eq 0 ]; then
+        CNT=$(helm ls | grep $HELM_APP | wc -l)
+        if [ $CNT -ne 0 ]; then
+            echo "=> Removing helm application $HELM_APP"
+            helm del --purge $HELM_APP
+        fi
+        echo "=> Installing $HELM_APP"
+        helm install --namespace monitoring --name $HELM_APP stable/$HELM_APP
+        check_rc $? ''
+    fi
+}
+
 do_setup_monitoring() {
     CLUSTER=$1
+
+    do_setup_glcoud
 
     echo "=> Using cluster $CLUSTER"
     gcloud config set container/cluster $CLUSTER
@@ -109,25 +136,12 @@ do_setup_monitoring() {
     do_install_helm_app grafana
 }
 
-
-do_install_helm_app() {
-    HELM_APP=$1
-    CNT=$(kubectl get pods --namespace monitoring | grep $HELM_APP | wc -l)
-    if [ $CNT -eq 0 ]; then
-        CNT=$(helm ls | grep $HELM_APP | wc -l)
-        if [ $CNT -ne 0 ]; then
-            echo "=> Removing helm application $HELM_APP"
-            helm del --purge $HELM_APP
-        fi
-        echo "=> Installing $HELM_APP"
-        helm install --namespace monitoring --name $HELM_APP stable/$HELM_APP
-        check_rc $? ''
-    fi
-}
-
-echo "=> Configuring gcloud..."
-gcloud config set project $GCP_PROJECT
-gcloud config set compute/region $GCP_REGION
-
-do_setup_monitoring $NAME_STAGING
-do_setup_monitoring $NAME_LIVE
+if [ $STAGING -eq 1 ] && [ $LIVE -eq 1 ]; then
+    echo "ERROR: please select only one of --live or --staging"
+elif [ $STAGING -eq 1 ]; then
+    do_setup_monitoring $NAME_STAGING
+elif [ $LIVE -eq 1 ]; then
+    do_setup_monitoring $NAME_LIVE
+else
+    echo "ERROR: please select one of --live or --staging"
+fi
